### ISSUE TITLE
webserver doesnt work correct

### ISSUE THREAD

**Issue by macmattes** [Edzelf/Esp-radio#19]
hi

thanks for this project, i use your software with a nodemcu clone from china and a vs1003 board.
streaming and audio works fine, but i am unable to use the webinterface. Some time the site loads nearly full, only the presets are missed , mostly i got a broken website which starts with "hr.open ( "GET", theUrl, false ...........  and shows the html code instead the site.
And if the site is visible i am unable to use any of the buttons, because loading never ends.
i have reflashed the esp some times also with a blink sketch and different flash sizes. nothing changed.
if i stop the site loading and use only the functions like "/?uppreset=1" it changes the channel without a delay. the other functions are also working. hope you can help to find my problem with the website.
i used safari or firefox on osx, both the same

**Comment by Edzelf** [comment]
Hello,
Maybe it is a problem with the vs1003 board.  Just remove the vs1003 and try the web-interface to see if it is loading.  I tried several Chinese boards without problems.  Send you debug output to ed.at.smallenburg.nl.  (.at. = @).
Ed.


Verzonden vanaf Samsung-tablet.

-------- Oorspronkelijk bericht --------
Van: macmattes <notifications@github.com> 
Datum: 08-09-2016  20:04  (GMT+01:00) 
Aan: Edzelf/Esp-radio <Esp-radio@noreply.github.com> 
Onderwerp: [PossibleSpam] [Edzelf/Esp-radio] webserver doesnt work correct (#19) 

hi

thanks for this project, i use your software with a nodemcu clone from china and a vs1003 board.

streaming and audio works fin, but i am unable to use the webinterface. Some time the site loads nearly full, only the presets are missed , mostly i got a broken website which starts with "hr.open ( "GET", theUrl, false ...........  and shows the html code instead the site.

And if the site is visible i am unable to use any of the buttons, because loading never ends.

i have reflashed the esp some times also with a blink sketch and different flash sizes. nothing changed.

if i stop the site loading and use only the functions like "/?uppreset=1" it changes the channel without a delay. the other functions are also working. hope you can help to find my problem with the website.

i used safari or firefox on osx, both the same

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Edzelf/Esp-radio","title":"Edzelf/Esp-radio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Edzelf/Esp-radio"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"webserver doesnt work correct (#19)"}],"action":{"name":"View Issue","url":"https://github.com/Edzelf/Esp-radio/issues/19"}}}

**Comment by Edzelf** [comment]
Are you sure that javascript works on osx?


Verzonden vanaf Samsung-tablet.

-------- Oorspronkelijk bericht --------
Van: macmattes <notifications@github.com> 
Datum: 08-09-2016  20:04  (GMT+01:00) 
Aan: Edzelf/Esp-radio <Esp-radio@noreply.github.com> 
Onderwerp: [PossibleSpam] [Edzelf/Esp-radio] webserver doesnt work correct (#19) 

hi

thanks for this project, i use your software with a nodemcu clone from china and a vs1003 board.

streaming and audio works fin, but i am unable to use the webinterface. Some time the site loads nearly full, only the presets are missed , mostly i got a broken website which starts with "hr.open ( "GET", theUrl, false ...........  and shows the html code instead the site.

And if the site is visible i am unable to use any of the buttons, because loading never ends.

i have reflashed the esp some times also with a blink sketch and different flash sizes. nothing changed.

if i stop the site loading and use only the functions like "/?uppreset=1" it changes the channel without a delay. the other functions are also working. hope you can help to find my problem with the website.

i used safari or firefox on osx, both the same

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Edzelf/Esp-radio","title":"Edzelf/Esp-radio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Edzelf/Esp-radio"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"webserver doesnt work correct (#19)"}],"action":{"name":"View Issue","url":"https://github.com/Edzelf/Esp-radio/issues/19"}}}

**Comment by Edzelf** [comment]
Could you try to use a different wifi network?  Maybe it something to do with the maximal packet size of your router.  You may also try to load a short and a long .txt file on the SPIFFS.  Your browser should be able to load this correctly (http://<IP>/file.txt or something like that).
Verzonden vanaf Samsung-tablet.

-------- Oorspronkelijk bericht --------
Van: macmattes <notifications@github.com> 
Datum: 08-09-2016  20:04  (GMT+01:00) 
Aan: Edzelf/Esp-radio <Esp-radio@noreply.github.com> 
Onderwerp: [PossibleSpam] [Edzelf/Esp-radio] webserver doesnt work correct (#19) 

hi

thanks for this project, i use your software with a nodemcu clone from china and a vs1003 board.

streaming and audio works fin, but i am unable to use the webinterface. Some time the site loads nearly full, only the presets are missed , mostly i got a broken website which starts with "hr.open ( "GET", theUrl, false ...........  and shows the html code instead the site.

And if the site is visible i am unable to use any of the buttons, because loading never ends.

i have reflashed the esp some times also with a blink sketch and different flash sizes. nothing changed.

if i stop the site loading and use only the functions like "/?uppreset=1" it changes the channel without a delay. the other functions are also working. hope you can help to find my problem with the website.

i used safari or firefox on osx, both the same

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Edzelf/Esp-radio","title":"Edzelf/Esp-radio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Edzelf/Esp-radio"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"webserver doesnt work correct (#19)"}],"action":{"name":"View Issue","url":"https://github.com/Edzelf/Esp-radio/issues/19"}}}

**Comment by macmattes** [comment]
hi

i am searching for a solution, it looks like a problem with the asyncwebserver or spiffs, i tried now without the decoder board and different flash spiff sizes, and also with a new nodemcu clone(same model)  nothing changes, the debug log shows the commands /?list uppreset.... all available, and i can see also that the t.md file is loaded from spiffs, but the index.html will not load.
a first test with a index.html without the script block fails, also.
i have send you my debug log, and i will search further

**Comment by macmattes** [comment]
hi

everything is fine with espradio, it works on my cellphone browser. thanks
courios

**Comment by Edzelf** [comment]
Take a look at this: https://support.zen.co.uk/kb/Knowledgebase/Changing-the-MTU-size-in-Mac-OS-X-10.6-to-10.9



Verzonden vanaf Samsung-tablet.

-------- Oorspronkelijk bericht --------
Van: macmattes <notifications@github.com> 
Datum: 11-09-2016  10:46  (GMT+01:00) 
Aan: Edzelf/Esp-radio <Esp-radio@noreply.github.com> 
Cc: Ed Smallenburg <ed@smallenburg.nl>, Comment <comment@noreply.github.com> 
Onderwerp: Re: [Edzelf/Esp-radio] webserver doesnt work correct (#19) 

hi

everything is fine with espradio, it works on my cellphone browser. thanks

courios

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Edzelf/Esp-radio","title":"Edzelf/Esp-radio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Edzelf/Esp-radio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@macmattes in #19: hi\r\n\r\neverything is fine with espradio, it works on my cellphone browser. thanks\r\ncourios"}],"action":{"name":"View Issue","url":"https://github.com/Edzelf/Esp-radio/issues/19#issuecomment-246169270"}}}
