### ISSUE TITLE
TFT display not working

### ISSUE THREAD

**Issue by pasagame** [Edzelf/Esp-radio#33]
I use a 1.8 TFT, but it does not work. I used standalone. (Test code), works properly. please look picture this link http://www.mx7.com/view2/zrLdZLyC7TSCjbPc

standalone (test code)
# include <Adafruit_GFX.h>  //Adafruit_GFX.h
# include <TFT_ILI9163C.h>  //TFT_ILI9163C.h
# include <SPI.h>  //SPI.h

// Color definitions for the TFT screen (if used)
# define  BLACK   0x0000
# define BLUE    0xF800
# define RED     0x001F
# define GREEN   0x07E0
# define CYAN    GREEN | BLUE
# define MAGENTA RED | BLUE
# define YELLOW  RED | GREEN
# define WHITE   0xFFFF
# define TFT_CS 15
# define TFT_DC 2

TFT_ILI9163C     tft = TFT_ILI9163C ( TFT_CS, TFT_DC ) ;

void setup() {
  SPI.begin() ;
  tft.begin() ;                                      // Init TFT interface
  tft.fillRect ( 0, 0, 160, 128, BLACK ) ;           // Clear screen does not work when rotated
  tft.setRotation ( 3 ) ;                            // Use landscape format
  tft.clearScreen() ;                                // Clear screen
  tft.setTextSize ( 1 ) ;                            // Small character font
  tft.setTextColor ( WHITE ) ;  
  tft.println ( "Starting" ) ;

}

void loop(){
  //
}

**Comment by Edzelf** [comment]
At the moment I have no possibility to look at the code.  If it works stand-alone, try to disconnect the VS1053 and the resetlines.
Verzonden vanaf Samsung-tablet.

-------- Oorspronkelijk bericht --------
Van: pasagame <notifications@github.com> 
Datum: 27-10-16  10:58  (GMT+01:00) 
Aan: Edzelf/Esp-radio <Esp-radio@noreply.github.com> 
Onderwerp: [PossibleSpam] [Edzelf/Esp-radio] TFT display not working (#33) 

I use a 1.8 TFT, but it does not work. I used standalone. (Test code), works properly. please look picture this link http://www.mx7.com/view2/zrLdZLyC7TSCjbPc

standalone (test code)

#include 

#include 

#include 

// Color definitions for the TFT screen (if used)

#define  BLACK   0x0000

#define BLUE    0xF800

#define RED     0x001F

#define GREEN   0x07E0

#define CYAN    GREEN | BLUE

#define MAGENTA RED | BLUE

#define YELLOW  RED | GREEN

#define WHITE   0xFFFF

#define TFT_CS 15

#define TFT_DC 2

TFT_ILI9163C     tft = TFT_ILI9163C ( TFT_CS, TFT_DC ) ;

void setup() {

  SPI.begin() ;

  tft.begin() ;                                      // Init TFT interface

  tft.fillRect ( 0, 0, 160, 128, BLACK ) ;           // Clear screen does not work when rotated

  tft.setRotation ( 3 ) ;                            // Use landscape format

  tft.clearScreen() ;                                // Clear screen

  tft.setTextSize ( 1 ) ;                            // Small character font

  tft.setTextColor ( WHITE ) ;


  tft.println ( "Starting" ) ;

}

void loop(){

//

}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Edzelf/Esp-radio","title":"Edzelf/Esp-radio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Edzelf/Esp-radio"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"TFT display not working (#33)"}],"action":{"name":"View Issue","url":"https://github.com/Edzelf/Esp-radio/issues/33"}}}

**Comment by pasagame** [comment]
until now i cannot use tft display.
