### ISSUE TITLE
Resume player after stop command

### ISSUE THREAD

**Issue by ohalushchak** [Edzelf/Esp-radio#51]
Tried to add a new command "resume". It should start to play music after it was stoped. For this command I do the next logic: 

hostreq = true ;

But it looks like something else is missing.

**Comment by Edzelf** [comment]
Looks good.  I will test it later.


Verzonden vanaf Samsung-tablet.

-------- Oorspronkelijk bericht --------
Van: ohalushchak <notifications@github.com> 
Datum: 25-12-16  15:56  (GMT+01:00) 
Aan: Edzelf/Esp-radio <Esp-radio@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Onderwerp: [Edzelf/Esp-radio] Resume player after stop command (#51) 

Tried to add a new command "resume". It should start to play music after it was stoped. For this command I do the next logic:
hostreq = true ;
But it looks like something else is missing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Edzelf/Esp-radio","title":"Edzelf/Esp-radio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Edzelf/Esp-radio"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Resume player after stop command (#51)"}],"action":{"name":"View Issue","url":"https://github.com/Edzelf/Esp-radio/issues/51"}}}

**Comment by ohalushchak** [comment]
Here is some additional information:
Request: /?stop=0
log: 
D: Command: stop with parameter 0
D: STOP requested
D: Stopping client
D: Song stopped correctly after 0 msec

Request: /?resume=0
log:
Command: resume with parameter 0
D: Connect to new host stream.mjoy.ua
D: Connect to stream.mjoy.ua on port 80, extension /
D: Connected to server
D: Server: Apache/2.4.7 (Ubuntu)
D: Last-Modified: Fri, 16 Oct 2015 10:26:07 GMT
D: Accept-Ranges: bytes
D: Content-Length: 11510
D: Connection: close
D: Content-Type: text/html
D: Switch to DATA, bitrate is 0
D: No data input
D: No data input
D: Trying other station/file...
D: STOP requested
D: 
D: 
D: Song stopped correctly after 0 msec
D: New preset/file requested
D: Connect to new host ua.uar.net:8000/galychyna
D: Slash in station
D: Connect to ua.uar.net on port 8000, extension /galychyna
D: Connected to server
D: Server: Icecast 2.4.1
D: Content-Type: audio/mpeg
D: Cache-Control: no-cache
D: Expires: Mon, 26 Jul 1997 05:00:00 GMT
D: Pragma: no-cache
D: Access-Control-Allow-Origin: *
D: icy-br:256
D: icy-description:This is only a trial
D: icy-genre:galychyna
D: icy-name:Galychyna FM
D: icy-pub:0
D: icy-url:http://www.galychyna.fm
D: icy-metaint:16000
D: Switch to DATA, bitrate is 256
D: Metadata block 16 bytes
D: Streamtitle found, 15 bytes
D: StreamTitle='';
D: Recovered from dataloss

**Comment by Edzelf** [comment]
Yes, it's clear.  The variable "host" is shortened in the function "connecttohost", making it unusable for a second call to this function.  I will change this and add the "resume" feature to the software within a few days.

**Comment by Edzelf** [comment]
Resume works now.  It is not yet implemented in the web interface.
